# Generated by Django 4.2.25 on 2025-11-11 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_counter_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='value',
        ),
        migrations.AddField(
            model_name='counter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
