# Generated by Django 4.2.25 on 2025-11-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_counter_value_counter_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='created_at',
        ),
    ]
